language: python
python:
  - "3.4"
cache:
  - pip
before_install:
    - sudo apt-get update -q
    - sudo apt-get build-dep python-numpy python-matplotlib python-scipy -y
# command to install dependencies
install:
    - pip install -r requirements.txt
    - pip install sip_models
    - pip install geccoinv
    - python setup.py install
# command to run tests
script: sh travis_test.sh
